#!/usr/bin/env bash
# Generate Ansible inventory from Terraform output.
# Run from the repository root after 'terraform apply'.
# Usage: ./scripts/generate-inventory.sh [ansible_user]

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TERRAFORM_DIR="$REPO_ROOT/terraform"
ANSIBLE_DIR="$REPO_ROOT/ansible"
HOSTS_FILE="$ANSIBLE_DIR/hosts"
ANSIBLE_USER="${1:-azureuser}"

if [[ ! -d "$TERRAFORM_DIR" ]]; then
  echo "Error: Terraform directory not found: $TERRAFORM_DIR" >&2
  exit 1
fi

cd "$TERRAFORM_DIR"
if ! terraform output -json runner_public_ips_list &>/dev/null; then
  echo "Error: Run 'terraform apply' first and ensure runner_public_ips_list output exists." >&2
  exit 1
fi

# Terraform output -json runner_public_ips_list returns a list like ["1.2.3.4","5.6.7.8"]
IPS_JSON=$(terraform output -json runner_public_ips_list)
IPS=()
if command -v jq &>/dev/null; then
  while IFS= read -r ip; do IPS+=("$ip"); done < <(echo "$IPS_JSON" | jq -r '.[]')
else
  while IFS= read -r line; do
    IPS+=("$line")
  done < <(echo "$IPS_JSON" | tr -d '[]"' | tr ',' '\n' | sed 's/^ *//;s/ *$//' | grep -v '^$')
fi

{
  echo "# Ansible inventory generated by scripts/generate-inventory.sh"
  echo "# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
  echo ""
  echo "[runners]"
  i=1
  for ip in "${IPS[@]}"; do
    echo "runner-$i ansible_host=$ip runner_name=runner-$i"
    (( i++ )) || true
  done
  echo ""
  echo "[runners:vars]"
  echo "ansible_user=$ANSIBLE_USER"
} > "$HOSTS_FILE"

echo "Wrote $HOSTS_FILE with ${#IPS[@]} host(s)."
cat "$HOSTS_FILE"
